Repository arduino-libraries/Arduino_Threads, pull requests merged in 2022-07, with the labels that each got.

#77 Update check-arduino action after library has been added to the index.
  .github/workflows/check-arduino.yml
Labels: type: enhancement, topic: infrastructure

#78 Remove examples designed to purposefully break Arduino_Threads.
  examples/Breaks_1/Breaks_1.ino
  examples/Breaks_1/SharedVariables.h
  examples/Breaks_1/Thread.inot
  examples/Breaks_2/Breaks_2.ino
  examples/Breaks_2/SharedVariables.h
  examples/Breaks_2/Thread.inot
  examples/Breaks_3/Breaks_3.ino
  examples/Breaks_3/SharedVariables.h
  examples/Breaks_3/Thread.inot
  examples/Breaks_4/Breaks_4.ino
  examples/Breaks_4/SharedVariables.h
  examples/Breaks_4/Thread.inot
  examples/Breaks_5/Breaks_5.ino
  examples/Breaks_5/SharedVariables.h
  examples/Breaks_5/Thread.inot
  examples/Breaks_6/Breaks_6.ino
  examples/Breaks_6/SharedVariables.h
  examples/Breaks_6/Thread.inot
Labels: type: enhancement, topic: code

#80 Provide links to patched Java IDE with multi-threading support.
  docs/README.md
Labels: topic: documentation, type: enhancement

#82 Thermostat example demonstrate advantages of source/sink vs shared in certain applications.
  examples/Threading_Basics/Thermostat/AirConditionerControl.inot
  examples/Threading_Basics/Thermostat/HeatingControl.inot
  examples/Threading_Basics/Thermostat/SharedVariables.h
  examples/Threading_Basics/Thermostat/TemperatureSensor.inot
  examples/Threading_Basics/Thermostat/TemperatureSensorReporter.inot
  examples/Threading_Basics/Thermostat/Thermostat.ino
Labels: type: enhancement, topic: code

#79 CLI Getting Started Guide
  docs/06-cli-getting-started.md
  docs/README.md
  docs/assets/boardlist.png
  docs/assets/compiled.png
  docs/assets/pathupdate.png
  docs/assets/uploaded.png
Labels: topic: documentation, type: enhancement

#86 Remove number prefix from documentation documents.
  docs/README.md
  docs/cli-getting-started.md
  docs/data-exchange.md
  docs/threading-basics.md
  docs/threadsafe-serial.md
  docs/threadsafe-spi.md
  docs/threadsafe-wire.md
Labels: topic: documentation, type: enhancement

#47 [Alex/inot-as-namespace] Provide workarounds for typical sketch idioms not working when using inot-as-class model.
  examples/Threading_Basics/Source_Sink_Counter/Source_Sink_Counter.ino
  examples/Threading_Basics/Source_Sink_LED/Source_Sink_LED.ino
  examples/Threading_Basics/Thermostat/Thermostat.ino
  src/Arduino_Threads.h
Labels: type: enhancement, topic: code

#90 Fix links (outdated URLs).
  README.md
Labels: topic: documentation, type: enhancement

#91 Fixing URLs.
  README.md
Labels: topic: documentation, type: enhancement

#92 Update documentation to show usage of CONNECT macro for connecting sinks and sources.
  docs/data-exchange.md
Labels: topic: documentation, type: enhancement
